spring:
  application:
    name: journalApp
  data:
    mongodb:
      uri: wlknefjksbkdf
      database: journaldb
      auto-index-creation: true
server:
  port: 8080
logging:
  level:
    net:
      springproject:
        journalApp: DEBUG

api:
  key:
    weather: SKDLbfhjkladsbkj