spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: journalApp
  data:
    mongodb:
      uri:
      database: journaldb
      auto-index-creation: true
server:
  port: 8080
logging:
  level:
    net:
      springproject:
        journalApp: DEBUG

api:
  key:
    weather:
#logging:
#  level:
#    root: off